"""empty message

Revision ID: 358aad5eb07a
Revises: 8665de4a9c61
Create Date: 2020-05-26 16:52:11.622587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358aad5eb07a'
down_revision = '8665de4a9c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencysync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('isSynced', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currencysync')
    # ### end Alembic commands ###
