"""empty message

Revision ID: 6b617aaae571
Revises: 358aad5eb07a
Create Date: 2020-05-26 17:49:44.665360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b617aaae571'
down_revision = '358aad5eb07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency', 'date')
    # ### end Alembic commands ###
